{{ config(materialized='view') }}

SELECT
    EXCHANGE_CODE,
    EXCHANGE_NAME,
    COUNTRY,
    CITY,
    TRADING_HOURS,
    TIMEZONE,
    CONCAT_WS('|', EXCHANGE_CODE) AS EXCHANGE_HKEY,
    'SEED.EXCHANGE' AS RECORD_SOURCE
FROM {{ ref('STG_ABC_BANK_EXCHANGE') }}